# Generated by Django 5.0.3 on 2024-04-16 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('weapon_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('weapon_name', models.CharField(max_length=50)),
                ('weapon_type', models.CharField(max_length=30)),
                ('damage_type', models.CharField(max_length=30)),
                ('ammo_type', models.CharField(max_length=30)),
                ('weapon_frame', models.CharField(max_length=30)),
                ('image_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Perk',
            fields=[
                ('perk_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('perk_name', models.CharField(max_length=50)),
                ('impact_change', models.FloatField()),
                ('range_change', models.FloatField()),
                ('stability_change', models.FloatField()),
                ('handling_change', models.FloatField()),
                ('reload_change', models.FloatField()),
                ('rpm_change', models.FloatField()),
                ('magazine_change', models.FloatField()),
                ('reload_change_percentage', models.FloatField()),
                ('damage_change', models.FloatField()),
                ('charge_time', models.FloatField()),
                ('charge_rate', models.FloatField()),
                ('guard_resistance', models.FloatField()),
                ('image_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Gun',
            fields=[
                ('weapon_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='destiny.weapon')),
                ('impact', models.FloatField()),
                ('range', models.FloatField()),
                ('stability', models.FloatField()),
                ('handling', models.FloatField()),
                ('reload_speed', models.FloatField()),
                ('rpm', models.FloatField()),
                ('magazine', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Weapon_Perks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.IntegerField()),
                ('perk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destiny.perk')),
                ('weapon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destiny.weapon')),
            ],
        ),
    ]
