# Generated by Django 5.0.3 on 2024-04-18 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destiny', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapons',
            fields=[
                ('weapon_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('weapon_name', models.CharField(max_length=50)),
                ('table_name', models.CharField(choices=[('Guns', 'Guns'), ('Sidearms', 'Sidearms'), ('Fusions', 'Fusions'), ('Launchers', 'Launchers'), ('Swords', 'Swords'), ('Bows', 'Bows')], max_length=10)),
                ('weapon_type', models.CharField(max_length=30)),
                ('damage_type', models.CharField(max_length=30)),
                ('ammo_type', models.CharField(max_length=30)),
                ('weapon_frame', models.CharField(max_length=30)),
                ('image_link', models.URLField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Perk',
            new_name='Perks',
        ),
        migrations.RenameModel(
            old_name='Gun',
            new_name='Guns',
        ),
        migrations.AlterField(
            model_name='guns',
            name='weapon_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='destiny.weapons'),
        ),
        migrations.AlterField(
            model_name='weapon_perks',
            name='weapon_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destiny.weapons'),
        ),
        migrations.DeleteModel(
            name='Weapon',
        ),
    ]
