# Generated by Django 5.0.3 on 2024-04-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destiny', '0002_weapons_rename_perk_perks_rename_gun_guns_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='weapon_perks',
            constraint=models.UniqueConstraint(fields=('weapon_id', 'perk_id'), name='unique_weapon_perk'),
        ),
    ]
