# Generated by Django 5.0.3 on 2024-04-22 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destiny', '0004_alter_guns_weapon_id_alter_weapon_perks_perk_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fusion',
            fields=[
                ('weapon_id', models.OneToOneField(db_column='weapon_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='destiny.weapons')),
                ('impact', models.FloatField()),
                ('range', models.FloatField()),
                ('stability', models.FloatField()),
                ('handling', models.FloatField()),
                ('reload_speed', models.FloatField()),
                ('charge_time', models.FloatField()),
                ('magazine', models.FloatField()),
                ('burst', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Launchers',
            fields=[
                ('weapon_id', models.OneToOneField(db_column='weapon_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='destiny.weapons')),
                ('blast_radius', models.FloatField()),
                ('velocity', models.FloatField()),
                ('stability', models.FloatField()),
                ('handling', models.FloatField()),
                ('reload_speed', models.FloatField()),
                ('rpm', models.FloatField()),
                ('magazine', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sidearms',
            fields=[
                ('weapon_id', models.OneToOneField(db_column='weapon_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='destiny.weapons')),
                ('blast_radius', models.FloatField()),
                ('velocity', models.FloatField()),
                ('range', models.FloatField()),
                ('stability', models.FloatField()),
                ('handling', models.FloatField()),
                ('reload_speed', models.FloatField()),
                ('rpm', models.FloatField()),
                ('magazine', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sword',
            fields=[
                ('weapon_id', models.OneToOneField(db_column='weapon_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='destiny.weapons')),
                ('impact', models.FloatField()),
                ('swing_speed', models.FloatField()),
                ('charge_rate', models.FloatField()),
                ('guard_resistance', models.FloatField()),
                ('guard_endurance', models.FloatField()),
                ('rpm', models.FloatField()),
                ('magazine', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='perks',
            name='blast_radius',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='perks',
            name='guard_endurance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='perks',
            name='magazine_change_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='perks',
            name='guard_resistance',
            field=models.FloatField(default=0),
        ),
    ]
