# Generated by Django 5.0.3 on 2024-04-23 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destiny', '0005_fusion_launchers_sidearms_sword_perks_blast_radius_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fusion',
            new_name='Fusions',
        ),
        migrations.RenameModel(
            old_name='Sword',
            new_name='Swords',
        ),
    ]
