# Generated by Django 5.0.3 on 2024-04-23 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destiny', '0006_rename_fusion_fusions_rename_sword_swords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bows',
            fields=[
                ('weapon_id', models.OneToOneField(db_column='weapon_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='destiny.weapons')),
                ('impact', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('stability', models.FloatField()),
                ('handling', models.FloatField()),
                ('reload_speed', models.FloatField()),
                ('draw_time', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='swords',
            name='magazine',
        ),
        migrations.RemoveField(
            model_name='swords',
            name='rpm',
        ),
    ]
