# Generated by Django 5.0.3 on 2024-04-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destiny', '0007_bows_remove_swords_magazine_remove_swords_rpm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base_dps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_type', models.CharField(max_length=30)),
                ('weapon_frame', models.CharField(max_length=30)),
                ('body_damage', models.FloatField()),
                ('crit_damge', models.FloatField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='base_dps',
            constraint=models.UniqueConstraint(fields=('weapon_type', 'weapon_frame'), name='unique_base_dps'),
        ),
    ]
