# Generated by Django 5.0.3 on 2024-04-26 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destiny', '0008_base_dps_base_dps_unique_base_dps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='base_dps',
            old_name='crit_damge',
            new_name='crit_damage',
        ),
    ]
